# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import yolo_pb2 as yolo__pb2


class YoloServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detection = channel.unary_unary(
                '/YoloService/Detection',
                request_serializer=yolo__pb2.RequestDetction.SerializeToString,
                response_deserializer=yolo__pb2.ResponseDetection.FromString,
                )


class YoloServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Detection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YoloServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detection': grpc.unary_unary_rpc_method_handler(
                    servicer.Detection,
                    request_deserializer=yolo__pb2.RequestDetction.FromString,
                    response_serializer=yolo__pb2.ResponseDetection.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'YoloService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class YoloService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Detection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YoloService/Detection',
            yolo__pb2.RequestDetction.SerializeToString,
            yolo__pb2.ResponseDetection.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
