# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yolo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yolo.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nyolo.proto\"\x1e\n\x0fRequestDetction\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"\'\n\x11ResponseDetection\x12\x12\n\ndetections\x18\x01 \x01(\x0c\x32\x42\n\x0bYoloService\x12\x33\n\tDetection\x12\x10.RequestDetction\x1a\x12.ResponseDetection\"\x00\x62\x06proto3'
)




_REQUESTDETCTION = _descriptor.Descriptor(
  name='RequestDetction',
  full_name='RequestDetction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='RequestDetction.img', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=44,
)


_RESPONSEDETECTION = _descriptor.Descriptor(
  name='ResponseDetection',
  full_name='ResponseDetection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='detections', full_name='ResponseDetection.detections', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['RequestDetction'] = _REQUESTDETCTION
DESCRIPTOR.message_types_by_name['ResponseDetection'] = _RESPONSEDETECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestDetction = _reflection.GeneratedProtocolMessageType('RequestDetction', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTDETCTION,
  '__module__' : 'yolo_pb2'
  # @@protoc_insertion_point(class_scope:RequestDetction)
  })
_sym_db.RegisterMessage(RequestDetction)

ResponseDetection = _reflection.GeneratedProtocolMessageType('ResponseDetection', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDETECTION,
  '__module__' : 'yolo_pb2'
  # @@protoc_insertion_point(class_scope:ResponseDetection)
  })
_sym_db.RegisterMessage(ResponseDetection)



_YOLOSERVICE = _descriptor.ServiceDescriptor(
  name='YoloService',
  full_name='YoloService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=87,
  serialized_end=153,
  methods=[
  _descriptor.MethodDescriptor(
    name='Detection',
    full_name='YoloService.Detection',
    index=0,
    containing_service=None,
    input_type=_REQUESTDETCTION,
    output_type=_RESPONSEDETECTION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_YOLOSERVICE)

DESCRIPTOR.services_by_name['YoloService'] = _YOLOSERVICE

# @@protoc_insertion_point(module_scope)
